[build]
  functions = "functions"  # Directory for Netlify Functions

[[redirects]]
  from = "/api/latest"  # Redirect for the API endpoint
  to = "/.netlify/functions/latest"  # Redirect to the Netlify Function
  status = 200
